# ma3_export.py
from __future__ import annotations

from pathlib import Path
from datetime import datetime
import re
from typing import Any, List

# Export-Verzeichnis (wird automatisch angelegt)
EXPORT_DIR = (Path(__file__).resolve().parent / "exports" / "ma3").resolve()


def _safe_filename(name: str) -> str:
    name = (name or "show").strip()
    name = re.sub(r"[^\w\-. ]+", "_", name, flags=re.UNICODE)
    name = re.sub(r"\s+", "_", name)
    return name[:80] or "show"


def _get_attr(obj: Any, *names: str, default: Any = "") -> Any:
    for n in names:
        if hasattr(obj, n):
            v = getattr(obj, n)
            if v is not None:
                return v
    return default


def _to_int(value: Any) -> int | None:
    try:
        if value is None:
            return None
        if isinstance(value, bool):
            return None
        return int(value)
    except Exception:
        return None


def _iter_items(db_show: Any) -> List[Any]:
    """
    Versucht Songs/Cues/Szenen aus verschiedenen möglichen Attributnamen zu holen.
    Passt zu typischen SQLAlchemy-Relationships.
    """
    for cand in ("songs", "cues", "scenes", "szenen"):
        if hasattr(db_show, cand):
            items = getattr(db_show, cand)
            try:
                return list(items)
            except TypeError:
                return []
    return []


def build_ma3_lua(db_show: Any) -> str:
    """
    Erzeugt ein grandMA3-Plugin (Lua) mit Entry-Function `main`.
    - Daten liegen in `local show = {...}`
    - `main()` erstellt/aktualisiert eine Sequence (Default 901 oder aus db_show)
    - Für jeden Cue: Store /O + Label
    """
    title = str(_get_attr(db_show, "title", "name", default="Show"))
    artist = str(_get_attr(db_show, "artist", default=""))
    venue = str(_get_attr(db_show, "venue", "location", default=""))
    date = str(_get_attr(db_show, "date", "show_date", default=""))

    # OPTIONAL: Wenn du eine Sequence-ID pro Show hast, wird sie genutzt.
    # Unterstützte Attributnamen (du kannst hier weitere ergänzen):
    seq_id_raw = _get_attr(db_show, "ma3_sequence_id", "sequence_id", "ma3_seq", default=None)
    seq_id = _to_int(seq_id_raw)  # None, wenn nicht gesetzt/ungültig

    def q(s: str) -> str:
        # minimal Lua-string-sicher: " -> '
        return (s or "").replace('"', "'")

    items = _iter_items(db_show)

    lines: List[str] = []
    lines.append("-- Auto-generated by Lichtassistent_v3")
    lines.append(f"-- Generated: {datetime.now().isoformat(timespec='seconds')}")
    lines.append("")
    lines.append("local show = {")
    lines.append(f'  title = "{q(title)}",')
    lines.append(f'  artist = "{q(artist)}",')
    lines.append(f'  venue  = "{q(venue)}",')
    lines.append(f'  date   = "{q(date)}",')
    if seq_id is not None and seq_id > 0:
        lines.append(f"  seq = {seq_id},")
    else:
        lines.append("  seq = nil,")
    lines.append("  cues = {")

    for i, it in enumerate(items, start=1):
        cue_name = str(_get_attr(it, "title", "name", default=f"Cue {i}"))
        mood = str(_get_attr(it, "mood", "stimmung", default=""))
        colors = str(_get_attr(it, "colors", "farben", default=""))

        lines.append("    {")
        lines.append(f"      index  = {i},")
        lines.append(f'      name   = "{q(cue_name)}",')
        lines.append(f'      mood   = "{q(mood)}",')
        lines.append(f'      colors = "{q(colors)}",')
        lines.append("    },")

    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("local function _safe(s)")
    lines.append("  if s == nil then return '' end")
    lines.append("  s = tostring(s)")
    lines.append("  s = string.gsub(s, '\"', \"'\")")
    lines.append("  s = string.gsub(s, \"[\\r\\n\\t]\", \" \")")
    lines.append("  s = string.gsub(s, \"|\", \"-\")")
    lines.append("  s = string.gsub(s, \"  +\", \" \")")
    lines.append("  return s")
    lines.append("end")

    lines.append("")
    lines.append("local function main(display_handle)")
    lines.append("  local seq = tonumber(show.seq) or 901  -- Fallback-Sequence")
    lines.append('  Printf(\"Lichtassistent MA3: Import -> \" .. tostring(show.title) .. \" | Seq \" .. tostring(seq))')
    lines.append('  Printf(\"Cues: \" .. tostring(#show.cues))')
    lines.append("")
    lines.append("  if #show.cues == 0 then")
    lines.append('    Printf(\"Keine Cues vorhanden – Abbruch.\")')
    lines.append("    return")
    lines.append("  end")
    lines.append("")
    lines.append("  CmdIndirectWait('ClearAll')")
    lines.append("")
    lines.append("  -- Update-Modus: Store /O (überschreibt Cue-Slots, löscht aber nicht die Sequence)")
    lines.append("  for _, c in ipairs(show.cues) do")
    lines.append("    local label = _safe(c.name)")
    lines.append("    if _safe(c.mood) ~= '' or _safe(c.colors) ~= '' then")
    lines.append("      label = label .. ' - ' .. _safe(c.mood) .. ' - ' .. _safe(c.colors)")
    lines.append("    end")
    lines.append("    CmdIndirectWait(string.format('Store Sequence %d Cue %d /O', seq, c.index))")
    lines.append("    CmdIndirectWait(string.format('Label Sequence %d Cue %d \"%s\"', seq, c.index, label))")
    lines.append("  end")
    lines.append("")
    lines.append("  CmdIndirectWait(string.format('Label Sequence %d \"%s\"', seq, _safe(show.title)))")
    lines.append("  CmdIndirectWait(string.format('Select Sequence %d', seq))")
    lines.append('  Printf(\"Fertig. Sequence/Cues angelegt oder aktualisiert.\")')
    lines.append("end")
    lines.append("")
    lines.append("return main")
    lines.append("")
    return "\n".join(lines)


def export_ma3_plugin_to_file(db_show: Any, export_dir: str | Path | None = None) -> Path:
    """
    Schreibt eine MA3-Lua-Datei auf Disk und gibt den Dateipfad als Path zurück.
    """
    out_dir = Path(export_dir).resolve() if export_dir else EXPORT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    title = str(_get_attr(db_show, "title", "name", default="Show"))
    filename = f"{_safe_filename(title)}_MA3.lua"
    file_path = (out_dir / filename).resolve()

    lua = build_ma3_lua(db_show)
    file_path.write_text(lua, encoding="utf-8")

    return file_path
