-- Auto-generated by Lichtassistent_v3
-- Generated: 2026-01-04T11:04:04

local show = {
  title = "Demo",
  artist = "",
  venue  = "",
  date   = "",
  seq = 101,
  cues = {
    {
      index  = 1,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 2,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 3,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 4,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 5,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 6,
      name   = "Jonas",
      mood   = "",
      colors = "",
    },
    {
      index  = 7,
      name   = "Clara",
      mood   = "",
      colors = "",
    },
    {
      index  = 8,
      name   = "Jonas",
      mood   = "",
      colors = "",
    },
    {
      index  = 9,
      name   = "Clara",
      mood   = "",
      colors = "",
    },
    {
      index  = 10,
      name   = "Jonas",
      mood   = "",
      colors = "",
    },
    {
      index  = 11,
      name   = "Scheinwerfer",
      mood   = "",
      colors = "",
    },
    {
      index  = 12,
      name   = "Clara",
      mood   = "",
      colors = "",
    },
    {
      index  = 13,
      name   = "Clara",
      mood   = "",
      colors = "",
    },
    {
      index  = 14,
      name   = "Jonas",
      mood   = "",
      colors = "",
    },
    {
      index  = 15,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 16,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 17,
      name   = "Clara",
      mood   = "",
      colors = "",
    },
    {
      index  = 18,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 19,
      name   = "Clara",
      mood   = "",
      colors = "",
    },
    {
      index  = 20,
      name   = "Jonas",
      mood   = "",
      colors = "",
    },
    {
      index  = 21,
      name   = "Clara",
      mood   = "",
      colors = "",
    },
    {
      index  = 22,
      name   = "Clara",
      mood   = "",
      colors = "",
    },
    {
      index  = 23,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 24,
      name   = "Clara",
      mood   = "",
      colors = "",
    },
    {
      index  = 25,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 26,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 27,
      name   = "",
      mood   = "",
      colors = "",
    },
    {
      index  = 28,
      name   = "Jonas",
      mood   = "",
      colors = "",
    },
    {
      index  = 29,
      name   = "Clara",
      mood   = "",
      colors = "",
    },
    {
      index  = 30,
      name   = "Nacht",
      mood   = "",
      colors = "",
    },
  }
}

local function _safe(s)
  if s == nil then return '' end
  s = tostring(s)
  s = string.gsub(s, '"', "'")
  s = string.gsub(s, "[\r\n\t]", " ")
  s = string.gsub(s, "|", "-")
  s = string.gsub(s, "  +", " ")
  return s
end

local function main(display_handle)
  local seq = tonumber(show.seq) or 901  -- Fallback-Sequence
  Printf("Lichtassistent MA3: Import -> " .. tostring(show.title) .. " | Seq " .. tostring(seq))
  Printf("Cues: " .. tostring(#show.cues))

  if #show.cues == 0 then
    Printf("Keine Cues vorhanden – Abbruch.")
    return
  end

  CmdIndirectWait('ClearAll')

  -- Update-Modus: Store /O (überschreibt Cue-Slots, löscht aber nicht die Sequence)
  for _, c in ipairs(show.cues) do
    local label = _safe(c.name)
    if _safe(c.mood) ~= '' or _safe(c.colors) ~= '' then
      label = label .. ' - ' .. _safe(c.mood) .. ' - ' .. _safe(c.colors)
    end
    CmdIndirectWait(string.format('Store Sequence %d Cue %d /O', seq, c.index))
    CmdIndirectWait(string.format('Label Sequence %d Cue %d "%s"', seq, c.index, label))
  end

  CmdIndirectWait(string.format('Label Sequence %d "%s"', seq, _safe(show.title)))
  CmdIndirectWait(string.format('Select Sequence %d', seq))
  Printf("Fertig. Sequence/Cues angelegt oder aktualisiert.")
end

return main
