-- Auto-generated by Lichtassistent_v3
-- Generated: 2025-12-21T14:56:25

local show = {
  title = "Demo Show",
  artist = "Demo Band",
  venue  = "",
  date   = "2025-12-22",
  seq = 1,
  cues = {
    {
      index  = 1,
      name   = "Demo Cue 1",
      mood   = "Demo Stimmung 1",
      colors = "Rot",
    },
    {
      index  = 2,
      name   = "Demo Cue 2",
      mood   = "Demo Stimmung 2",
      colors = "Blau",
    },
  }
}

local function _safe(s)
  if s == nil then return '' end
  s = tostring(s)
  s = string.gsub(s, '"', "'")
  s = string.gsub(s, "[\r\n\t]", " ")
  s = string.gsub(s, "|", "-")
  s = string.gsub(s, "  +", " ")
  return s
end

local function main(display_handle)
  local seq = tonumber(show.seq) or 901  -- Fallback-Sequence
  Printf("Lichtassistent MA3: Import -> " .. tostring(show.title) .. " | Seq " .. tostring(seq))
  Printf("Cues: " .. tostring(#show.cues))

  if #show.cues == 0 then
    Printf("Keine Cues vorhanden – Abbruch.")
    return
  end

  CmdIndirectWait('ClearAll')

  -- Update-Modus: Store /O (überschreibt Cue-Slots, löscht aber nicht die Sequence)
  for _, c in ipairs(show.cues) do
    local label = _safe(c.name)
    if _safe(c.mood) ~= '' or _safe(c.colors) ~= '' then
      label = label .. ' - ' .. _safe(c.mood) .. ' - ' .. _safe(c.colors)
    end
    CmdIndirectWait(string.format('Store Sequence %d Cue %d /O', seq, c.index))
    CmdIndirectWait(string.format('Label Sequence %d Cue %d "%s"', seq, c.index, label))
  end

  CmdIndirectWait(string.format('Label Sequence %d "%s"', seq, _safe(show.title)))
  CmdIndirectWait(string.format('Select Sequence %d', seq))
  Printf("Fertig. Sequence/Cues angelegt oder aktualisiert.")
end

return main
