-- Auto-generated by Lichtassistent_v3
-- Generated: 2025-12-17T12:58:39

local show = {
  title = "Geiler Igel",
  artist = "Igel",
  venue  = "",
  date   = "2025-12-19",
  seq = 2,
  cues = {
    {
      index  = 1,
      name   = "Miste",
      mood   = "Miste",
      colors = "Weihnachten",
    },
    {
      index  = 2,
      name   = "Fuchs",
      mood   = "Fuchs",
      colors = "",
    },
    {
      index  = 3,
      name   = "Pferd",
      mood   = "pferd",
      colors = "Blau",
    },
    {
      index  = 4,
      name   = "weihnachten",
      mood   = "Heilig",
      colors = "",
    },
    {
      index  = 5,
      name   = "asd",
      mood   = "asd",
      colors = "",
    },
    {
      index  = 6,
      name   = "asdasda",
      mood   = "",
      colors = "adadadadas",
    },
    {
      index  = 7,
      name   = "asda",
      mood   = "asd",
      colors = "sdasd",
    },
    {
      index  = 8,
      name   = "dasda",
      mood   = "da",
      colors = "sda",
    },
    {
      index  = 9,
      name   = "asd",
      mood   = "adas",
      colors = "asd",
    },
    {
      index  = 10,
      name   = "jzgjgzjzg",
      mood   = "jg",
      colors = "gzjgjg",
    },
    {
      index  = 11,
      name   = "jgzj",
      mood   = "jgjgzjg",
      colors = "jgzjg",
    },
    {
      index  = 12,
      name   = "Song 12",
      mood   = "",
      colors = "",
    },
    {
      index  = 13,
      name   = "rgrdg",
      mood   = "rdg",
      colors = "drg",
    },
    {
      index  = 14,
      name   = "grdg",
      mood   = "rgdrg",
      colors = "rgrd",
    },
    {
      index  = 15,
      name   = "drgrg",
      mood   = "",
      colors = "drrg",
    },
    {
      index  = 16,
      name   = "wdwdad",
      mood   = "awd",
      colors = "rgqa",
    },
    {
      index  = 17,
      name   = "adw",
      mood   = "awdw",
      colors = "wad",
    },
    {
      index  = 18,
      name   = "fesf",
      mood   = "efs",
      colors = "fes",
    },
    {
      index  = 19,
      name   = "dawd",
      mood   = "adawd",
      colors = "awdwa",
    },
    {
      index  = 20,
      name   = "esef",
      mood   = "e",
      colors = "sef",
    },
    {
      index  = 21,
      name   = "efef",
      mood   = "efs",
      colors = "fef",
    },
    {
      index  = 22,
      name   = "fef",
      mood   = "sef",
      colors = "fes",
    },
    {
      index  = 23,
      name   = "asd",
      mood   = "asd",
      colors = "asd",
    },
    {
      index  = 24,
      name   = "asd",
      mood   = "",
      colors = "asd",
    },
    {
      index  = 25,
      name   = "asd",
      mood   = "",
      colors = "asd",
    },
  }
}

local function _safe(s)
  if s == nil then return '' end
  s = tostring(s)
  s = string.gsub(s, '"', "'")
  s = string.gsub(s, "[\r\n\t]", " ")
  s = string.gsub(s, "|", "-")
  s = string.gsub(s, "  +", " ")
  return s
end

local function main(display_handle)
  local seq = tonumber(show.seq) or 901  -- Fallback-Sequence
  Printf("Lichtassistent MA3: Import -> " .. tostring(show.title) .. " | Seq " .. tostring(seq))
  Printf("Cues: " .. tostring(#show.cues))

  if #show.cues == 0 then
    Printf("Keine Cues vorhanden – Abbruch.")
    return
  end

  CmdIndirectWait('ClearAll')

  -- Update-Modus: Store /O (überschreibt Cue-Slots, löscht aber nicht die Sequence)
  for _, c in ipairs(show.cues) do
    local label = _safe(c.name)
    if _safe(c.mood) ~= '' or _safe(c.colors) ~= '' then
      label = label .. ' - ' .. _safe(c.mood) .. ' - ' .. _safe(c.colors)
    end
    CmdIndirectWait(string.format('Store Sequence %d Cue %d /O', seq, c.index))
    CmdIndirectWait(string.format('Label Sequence %d Cue %d "%s"', seq, c.index, label))
  end

  CmdIndirectWait(string.format('Label Sequence %d "%s"', seq, _safe(show.title)))
  CmdIndirectWait(string.format('Select Sequence %d', seq))
  Printf("Fertig. Sequence/Cues angelegt oder aktualisiert.")
end

return main
