-- Auto-generated by Lichtassistent_v3
-- Generated: 2025-12-15T11:34:54

local show = {
  title = "Test Show",
  artist = "Test Artist",
  venue  = "",
  date   = "2025-12-16",
  cues = {
    {
      index  = 1,
      name   = "Hoch",
      mood   = "romatic",
      colors = "Rot",
    },
    {
      index  = 2,
      name   = "runter",
      mood   = "hastig",
      colors = "blau",
    },
  }
}

local function main(display_handle)
  Printf("Lichtassistent MA3 Import: " .. tostring(show.title))
  Printf("Cues: " .. tostring(#show.cues))
  for _, c in ipairs(show.cues) do
    Printf(string.format("Cue %s: %s | mood=%s | colors=%s", tostring(c.index), tostring(c.name), tostring(c.mood), tostring(c.colors)))
  end
end

return main
